version: "3.9"

services:
    db: 
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: flask_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./db/var/lib/mysql:/var/lib/mysql